/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Zady-
 */
public class Informacion extends javax.swing.JFrame {

    /**
     * Creates new form Informacion
     */
    public Informacion() {
        initComponents();
        this.setSize(400, 520);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Acerca de");
        getContentPane().setLayout(new java.awt.GridLayout(1, 1, 20, 20));

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("          Intituto Tecnológico y de Estudios Superiores de Monterrey\n                                       Campus Estado de México\n\n                  Jesús Zabdiel Sánchez Chávez A01374964 ISC\n\n                 Proyecto final Programación Orientada a Objetos\n\n\n                                    Acerca de esta aplicación:\n\n          Esta aplicación es un administrador de estacionamiento. \n          Permite regsitrar entradas y salidas de cada uno de los \n          vehículos que ingresan (Automóvil, Camión, Motocicleta,\n          Bicicleta), así como calcular la tarifa correspondiente. \n          Al momento de dar salida a un vehículo se generará el \n          ticket correspondiente al uso del estcionamiento. Este\n          estacionamiento cuenta con espacio para almacenar \n          hasta 100 vehículos.\n\n          **Nota\n          La aplicación está diseñada para que esté abierta a todo\n          momento al igual que un estacionamiento 24hrs. Debido\n          a lo anterior, al cerrar la aplicación, esta se resetea, es\n          decir, se supone que todos los vehículos abandonaron el\n          estacionamiento y todo vuelve a empezar. Sin embargo,\n          los registrosde entradas y salidas de vehículos permancen.\n\n\n");
        getContentPane().add(jTextArea1);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
