
import java.io.PrintWriter;
import javax.swing.JFrame;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Zady-
 */
public class Salida extends javax.swing.JFrame {

    /**
     * Creates new form Salida
     */
    Administrador principal;
    Seleccion seleccion;
    Ticket ventanaTicket;
    String ticket;
    
    public Salida(Seleccion seleccion, Administrador principal) {
        initComponents();
        this.principal = principal;
        this.seleccion = seleccion;
        this.ventanaTicket = new Ticket(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        textBuscar = new javax.swing.JTextField();
        btnBuscarVehiculo = new javax.swing.JButton();
        lbTotal = new javax.swing.JLabel();
        btnTicket = new javax.swing.JButton();
        lbError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Sacar vehículo");
        setResizable(false);
        setSize(new java.awt.Dimension(600, 450));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setLayout(new java.awt.GridLayout(6, 1, 0, 20));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Introduzca su número de ticket o placas");
        jPanel1.add(jLabel1);

        textBuscar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(textBuscar);

        btnBuscarVehiculo.setText("Buscar");
        btnBuscarVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarVehiculoActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscarVehiculo);

        lbTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTotal.setText("Total a pagar: $ ");
        jPanel1.add(lbTotal);

        btnTicket.setText("Ticket");
        btnTicket.setEnabled(false);
        btnTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTicketActionPerformed(evt);
            }
        });
        jPanel1.add(btnTicket);

        lbError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lbError);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textBuscarActionPerformed
        // TODO add handling code here:
    }//GEN-LAST:event_textBuscarActionPerformed

    public void setTextField(){
        this.textBuscar.setText(null);
        this.btnBuscarVehiculo.setEnabled(true);
        this.lbError.setText(null);
        this.lbTotal.setText("Total a pagar: $");
        this.btnTicket.setEnabled(false);
   }
    private void btnBuscarVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarVehiculoActionPerformed
        double tarifa;
        Vehiculo[] estacionamiento = this.seleccion.getEstacionamiento();
        boolean encontrado = false;
        String datosVehiculo = this.textBuscar.getText().toUpperCase();
        this.textBuscar.setText(null);
        for (int i =0; i<seleccion.getEstacionamiento().length;i++) {
            Vehiculo vehi = estacionamiento[i];
            if((vehi != null) && (vehi instanceof Bicicleta)){
                if(vehi.getTicket().equals(datosVehiculo)){
                    tarifa = vehi.calcularTarifa();
                    this.btnBuscarVehiculo.setEnabled(false);
                    this.lbTotal.setText(this.lbTotal.getText() + tarifa);
                    encontrado = true;
                    seleccion.registrarSalida(vehi);
                    this.ticket = vehi.formatearTicket(tarifa);
                    this.btnTicket.setEnabled(true);
                    estacionamiento[i] = null;
                    principal.setTextLugares();
                    
                    break;
                }
            }else{
                if((vehi != null)&&(vehi.getPlacas().equals(datosVehiculo) || 
                                    vehi.getTicket().equals(datosVehiculo))){
                    tarifa = vehi.calcularTarifa();
                    this.btnBuscarVehiculo.setEnabled(false);
                    this.lbTotal.setText(this.lbTotal.getText() + tarifa);
                    encontrado = true;
                    seleccion.registrarSalida(vehi);
                    this.ticket = vehi.formatearTicket(tarifa);
                    this.btnTicket.setEnabled(true);
                    estacionamiento[i] = null;
                    principal.setTextLugares();
                    break;
                }
            }            
        }
        if(encontrado == false){
            this.lbError.setText("Vehículo no encontrado. Por favor, "
                            + "verifica los datos ingresados");           
        }
    }//GEN-LAST:event_btnBuscarVehiculoActionPerformed

    private void btnTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTicketActionPerformed
        ventanaTicket.setSize(235, 400);
        ventanaTicket.setResizable(false);
        ventanaTicket.setTicketText(ticket);
        ventanaTicket.setLocationRelativeTo(this);
        ventanaTicket.setVisible(true);
    }//GEN-LAST:event_btnTicketActionPerformed

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarVehiculo;
    private javax.swing.JButton btnTicket;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbError;
    private javax.swing.JLabel lbTotal;
    private javax.swing.JTextField textBuscar;
    // End of variables declaration//GEN-END:variables
}
