/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Zady-
 */
public class Ticket extends javax.swing.JFrame {

    /**
     * Creates new form Ticket
     */
    Salida salida;
    public Ticket(Salida salida) {
        initComponents();
        this.salida = salida;
    }
    
    public void setTicketText(String text){
        this.ticketText.setText(text);       
    }




    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        ticketText = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ticket");

        ticketText.setEditable(false);
        ticketText.setColumns(20);
        ticketText.setRows(5);
        jScrollPane1.setViewportView(ticketText);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea ticketText;
    // End of variables declaration//GEN-END:variables
}
