/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Zady-
 */
public class CalculadoraRacionales extends javax.swing.JFrame {

    /**
     * Creates new form CalculadoraRacionales
     */
    public CalculadoraRacionales() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tfNumerador1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfDenominador1 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        tfNumerador2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfDenominador2 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        buttonSum = new javax.swing.JButton();
        buttonRes = new javax.swing.JButton();
        buttonMul = new javax.swing.JButton();
        buttonDiv = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jlResultado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Calculadora de Racionales");
        getContentPane().add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jPanel1.setLayout(new java.awt.GridLayout(4, 0));

        jLabel2.setText("Fracción 1: ");
        jPanel2.add(jLabel2);

        tfNumerador1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfNumerador1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        tfNumerador1.setMinimumSize(new java.awt.Dimension(20, 35));
        tfNumerador1.setPreferredSize(new java.awt.Dimension(60, 35));
        tfNumerador1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNumerador1ActionPerformed(evt);
            }
        });
        jPanel2.add(tfNumerador1);

        jLabel3.setText("/");
        jPanel2.add(jLabel3);

        tfDenominador1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfDenominador1.setPreferredSize(new java.awt.Dimension(60, 35));
        tfDenominador1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDenominador1ActionPerformed(evt);
            }
        });
        jPanel2.add(tfDenominador1);

        jPanel1.add(jPanel2);

        jLabel4.setText("Fracción 2: ");
        jPanel3.add(jLabel4);

        tfNumerador2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfNumerador2.setPreferredSize(new java.awt.Dimension(60, 35));
        jPanel3.add(tfNumerador2);

        jLabel5.setText("/");
        jPanel3.add(jLabel5);

        tfDenominador2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfDenominador2.setPreferredSize(new java.awt.Dimension(60, 35));
        jPanel3.add(tfDenominador2);

        jPanel1.add(jPanel3);

        jPanel4.setLayout(new java.awt.GridLayout(2, 4));

        buttonSum.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buttonSum.setText("Sumar");
        buttonSum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSumActionPerformed(evt);
            }
        });
        jPanel4.add(buttonSum);

        buttonRes.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buttonRes.setText("Restar");
        buttonRes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonResActionPerformed(evt);
            }
        });
        jPanel4.add(buttonRes);

        buttonMul.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buttonMul.setText("Multiplicar");
        buttonMul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMulActionPerformed(evt);
            }
        });
        jPanel4.add(buttonMul);

        buttonDiv.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buttonDiv.setText("Dividir");
        buttonDiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDivActionPerformed(evt);
            }
        });
        jPanel4.add(buttonDiv);

        jPanel1.add(jPanel4);

        jPanel5.setLayout(new java.awt.BorderLayout());

        jlResultado.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlResultado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlResultado.setText("Resultado");
        jPanel5.add(jlResultado, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel5);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfDenominador1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDenominador1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfDenominador1ActionPerformed

    private void buttonSumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSumActionPerformed
        int num1 = Integer.parseInt(tfNumerador1.getText());
        int den1 = Integer.parseInt(tfDenominador1.getText());
        int num2 = Integer.parseInt(tfNumerador2.getText());
        int den2 = Integer.parseInt(tfDenominador2.getText());
        
        Racional a = new Racional(num1, den1);
        Racional b = new Racional(num2, den2);
        
        jlResultado.setText(a.sumar(b).toString());
        
    }//GEN-LAST:event_buttonSumActionPerformed

    private void buttonResActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonResActionPerformed
        int num1 = Integer.parseInt(tfNumerador1.getText());
        int den1 = Integer.parseInt(tfDenominador1.getText());
        int num2 = Integer.parseInt(tfNumerador2.getText());
        int den2 = Integer.parseInt(tfDenominador2.getText());
        
        Racional a = new Racional(num1, den1);
        Racional b = new Racional(num2, den2);
        
        jlResultado.setText(a.restar(b).toString());
    }//GEN-LAST:event_buttonResActionPerformed

    private void buttonMulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMulActionPerformed
        int num1 = Integer.parseInt(tfNumerador1.getText());
        int den1 = Integer.parseInt(tfDenominador1.getText());
        int num2 = Integer.parseInt(tfNumerador2.getText());
        int den2 = Integer.parseInt(tfDenominador2.getText());
        
        Racional a = new Racional(num1, den1);
        Racional b = new Racional(num2, den2);
        
        jlResultado.setText(a.multiplicar(b).toString());
    }//GEN-LAST:event_buttonMulActionPerformed

    private void buttonDivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDivActionPerformed
        int num1 = Integer.parseInt(tfNumerador1.getText());
        int den1 = Integer.parseInt(tfDenominador1.getText());
        int num2 = Integer.parseInt(tfNumerador2.getText());
        int den2 = Integer.parseInt(tfDenominador2.getText());
        
        Racional a = new Racional(num1, den1);
        Racional b = new Racional(num2, den2);
        
        jlResultado.setText(a.dividir(b).toString());
    }//GEN-LAST:event_buttonDivActionPerformed

    private void tfNumerador1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNumerador1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNumerador1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculadoraRacionales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculadoraRacionales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculadoraRacionales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculadoraRacionales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculadoraRacionales().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonDiv;
    private javax.swing.JButton buttonMul;
    private javax.swing.JButton buttonRes;
    private javax.swing.JButton buttonSum;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel jlResultado;
    private javax.swing.JTextField tfDenominador1;
    private javax.swing.JTextField tfDenominador2;
    private javax.swing.JTextField tfNumerador1;
    private javax.swing.JTextField tfNumerador2;
    // End of variables declaration//GEN-END:variables
}
